name: CI

on: [push, workflow_dispatch, pull_request]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Java install
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - name: Flutter install
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: dev

      - name: Download dependencies
        run: flutter pub get

      - name: Formatting code
        run: dart format lib

      - name: Unit tests
        run: flutter test

      - name: Run flutter lints
        run: flutter analyze

      - name: Decode google.json
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        run: echo "$GOOGLE_JSON" > android/app/google-services.json

      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Uploading to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIRE_ID}}
          token: ${{secrets.FIRE_TOKEN}}
          file: build/app/outputs/flutter-apk/app.apk